name: Build
on:
  pull_request:
  push:
    branches: [main]
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true
    - name: Build package
      run: |
        mkdir -p artifacts/packages
        dotnet pack -o artifacts/packages
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: artifacts/packages/*.nupkg
